version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  backend1:
    image: hashicorp/http-echo
    command: -text="Hello from Backend 1!"
    ports:
      - "5678:5678"

  backend2:
    image: hashicorp/http-echo
    command: -text="Hello from Backend 2!"
    ports:
      - "5679:5678"

  backend3:
    image: hashicorp/http-echo
    command: -text="Hello from Backend 3!"
    ports:
      - "5680:5678"
